- nmae: delete app directory
  ansible.builtin.file:
  path: "{{ app_location }}"
  state : absent
  #ignore_errors: yes

- nmae: delete app directory
  ansible.builtin.file:
  path: "{{ app_location }}"
  state : directory  

- name: download and extract code 
